### ISSUE TITLE
TypeError: Cannot read property 'map' of null

### ISSUE THREAD

**Issue by amimas** [azu/textlint-rule-en-max-word-count#3]
I have a markdown file with the following contents:

```markdown

### JMS Messaging Properties

#### `ep.jms.type`

Developer Default: `org.apache.activemq.pool.PooledConnectionFactory`

The Java Class type of the JMS Broker Connection Factory.	

#### `ep.jms.factory`

Developer Default: `org.apache.activemq.jndi.JNDIReferenceFactory`

The JNDI resource factory used by the application.	

#### `ep.jms.url`

Developer Default: `tcp://localhost:61616`

The URL of the JMS broker.

```

I am using textlint version `11.2.5` and this rule version `1.0.1`. This rule is failing to execute textlint on the file where I have the above contents. If I get rid of that content, everything runs fine. I even removed all the other contents except this, and still unable to execute textlint. I am getting the following error:

I can't figure out what is wrong with the above markdown snippet and why this rule is failing to execute because of it.

```text
✖ Stack trace
TypeError: Cannot read property 'map' of null
at /Users/amimas/projects/documentation-sites/docs/docs/deployment/configuration/environment-config.md
    at module.exports (/Users/amimas/projects/documentation-sites/docs/website/node_modules/split-string-words/index.js:5:9)
    at /Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint-rule-en-max-word-count/lib/textlint-rule-en-max-word-count.js:48:56
    at Array.forEach (<anonymous>)
    at /Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint-rule-en-max-word-count/lib/textlint-rule-en-max-word-count.js:36:19
    at /Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/task/promise-event-emitter.js:26:36
    at Array.forEach (<anonymous>)
    at RuleTypeEmitter.PromiseEventEmitter.emit (/Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/task/promise-event-emitter.js:25:38)
    at Controller.enter (/Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/task/textlint-core-task.js:130:51)
    at Controller.__execute (/Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/ast-traverse/lib/ast-traverse/src/index.js:45:31)
    at Controller.traverse (/Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/ast-traverse/lib/ast-traverse/src/index.js:116:28)
    at TextLintCoreTask.startTraverser (/Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/task/textlint-core-task.js:125:28)
    at TextLintCoreTask.start (/Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/task/linter-task.js:34:14)
    at /Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/task/task-runner.js:26:18
    at new Promise (<anonymous>)
    at Function.TaskRunner.process (/Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/task/task-runner.js:14:16)
    at LinterProcessor.process (/Users/amimas/projects/documentation-sites/docs/website/node_modules/textlint/node_modules/@textlint/kernel/lib/kernel/src/linter/linter-processor.js:31:38)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

```

**Comment by amimas** [comment]
I should have waited a few more minutes. Just found out the cause of the issue. I had several spaces at the end of each of the description lines. Once I removed those, textlint is now executing properly.

It was a bit difficult to find the issue. Not sure if textlint can be more helpful with the error message here, but that would be very useful.

**Comment by azu** [comment]
I think that this issue is actual bug.
So, I've reopened.

**Comment by amimas** [comment]
Thanks a lot for thr quick fix!!
